[1] "test start"
[1] "Thu Jan 20 14:46:09 2022"
[1] "test start"
[1] "Mon Jan 24 09:30:50 2022"
[1] "Testing on files:"
[1] "./test/test_data/BisonGulchQuads.envi"      
[2] "./test/test_data/TwelveMileGulchQuads1.envi"
[3] "./test/test_data/TwelveMileGulchQuads2.envi"
[1] "Configuration files:"
[1] "./test/test_configs/test_config_1 copy 2.json"
[2] "./test/test_configs/test_config_1 copy 3.json"
[3] "./test/test_configs/test_config_1 copy 4.json"
[4] "./test/test_configs/test_config_1 copy 5.json"
[5] "./test/test_configs/test_config_1 copy.json"  
[6] "./test/test_configs/test_config_1.json"       
[1] "8 Cores Detected for processing..."
[1] "Tile based processing complete"
[[1]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4964584 265.2    7555671 403.6  7555671 403.6
Vcells 9798478  74.8   37507316 286.2 58605180 447.2

[[2]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4961786 265.0    7555671 403.6  7555671 403.6
Vcells 9788681  74.7   31274854 238.7 61083697 466.1

[[3]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4964577 265.2    7555671 403.6  7555671 403.6
Vcells 9798478  74.8   37563060 286.6 58692279 447.8

[[4]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4961786 265.0    7555671 403.6  7555671 403.6
Vcells 9788681  74.7   31170784 237.9 60880437 464.5

[1] "Mon Jan 24 09:31:54 2022\nTest completed with warnings for config: \n./test/test_configs/test_config_1 copy 2.json\nand file: \n./test/test_data/BisonGulchQuads.envi\nwarnings: \nsimpleWarning in doTryCatch(return(expr), name, parentenv, handler): NAs introduced by coercion\n"
[1] "8 Cores Detected for processing..."
[1] "Tile based processing complete"
[[1]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4962920 265.1    7555674 403.6  7555674 403.6
Vcells 8417122  64.3   29414428 224.5 57449895 438.4

[[2]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4961690 265.0    7555674 403.6  7555674 403.6
Vcells 8412668  64.2   31125538 237.5 60792064 463.9

[[3]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4962920 265.1    7555674 403.6  7555674 403.6
Vcells 8417122  64.3   29432816 224.6 57818113 441.2

[[4]]
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4961690 265.0    7555674 403.6  7555674 403.6
Vcells 8412668  64.2   31117365 237.5 60775420 463.7

[1] "Mon Jan 24 09:33:04 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/test_config_1 copy 3.json\nError: \nError in .local(x, filename, ...): Attempting to write a file to a path that does not exist:\n  ./test/test_outputs/pred_./test/test_data\n"
[1] "8 Cores Detected for processing..."
NULL
NULL
NULL
NULL
NULL
NULL
NULL
NULL
NULL
No traceback available 
[1] "foo"
[1] "test start"
[1] "Tue Jan 25 14:03:48 2022"
[1] "Testing on files:"
[1] "./test/test_data/BisonGulchQuads.envi"      
[2] "./test/test_data/TwelveMileGulchQuads1.envi"
[3] "./test/test_data/TwelveMileGulchQuads2.envi"
[1] "Configuration files:"
[1] "./test/test_configs/fg1_1.json"     "./test/test_configs/fg2_1.json"    
[3] "./test/test_configs/species_1.json"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:06:20 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/fg1_1.json\nError: \nError in {: task 1 failed - \"arguments imply differing number of rows: 1051, 0\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:09:46 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/fg2_1.json\nError: \nError in serialize(data, node$con): error writing to connection\n"
[1] "Tue Jan 25 14:09:57 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/species_1.json\nError: \nError in unserialize(node$con): error reading from connection\n"
[1] "test start"
[1] "Tue Jan 25 14:11:08 2022"
[1] "Testing on files:"
[1] "./test/test_data/BisonGulchQuads.envi"      
[2] "./test/test_data/TwelveMileGulchQuads1.envi"
[3] "./test/test_data/TwelveMileGulchQuads2.envi"
[1] "Configuration files:"
[1] "./test/test_configs/fg1_1.json"     "./test/test_configs/fg2_1.json"    
[3] "./test/test_configs/species_1.json"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:11:57 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/fg1_1.json\nError: \nError in {: task 1 failed - \"arguments imply differing number of rows: 1051, 0\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:13:08 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/fg2_1.json\nError: \nError in {: task 1 failed - \"arguments imply differing number of rows: 1051, 0\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:14:12 2022\nTest failed for file:\n./test/test_data/BisonGulchQuads.envi using config: \n./test/test_configs/species_1.json\nError: \nError in {: task 1 failed - \"arguments imply differing number of rows: 1051, 0\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:15:14 2022\nTest failed for file:\n./test/test_data/TwelveMileGulchQuads1.envi using config: \n./test/test_configs/fg1_1.json\nError: \nError in {: task 1 failed - \"error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': dims [product 10624992] do not match the length of object [0]\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:16:12 2022\nTest failed for file:\n./test/test_data/TwelveMileGulchQuads1.envi using config: \n./test/test_configs/fg2_1.json\nError: \nError in {: task 1 failed - \"error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': dims [product 10624992] do not match the length of object [0]\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:17:11 2022\nTest failed for file:\n./test/test_data/TwelveMileGulchQuads1.envi using config: \n./test/test_configs/species_1.json\nError: \nError in {: task 1 failed - \"error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': dims [product 10624992] do not match the length of object [0]\"\n"
[1] "8 Cores Detected for processing..."
[1] "Tue Jan 25 14:18:07 2022\nTest failed for file:\n./test/test_data/TwelveMileGulchQuads2.envi using config: \n./test/test_configs/fg1_1.json\nError: \nError in checkForRemoteErrors(val): 3 nodes produced errors; first error: incorrect number of layer names\n"
[1] "Tue Jan 25 14:18:07 2022\nTest completed with warnings for config: \n./test/test_configs/fg2_1.json\nand file: \n./test/test_data/TwelveMileGulchQuads2.envi\nwarnings: \nsimpleWarning in file(con, \"w\"): cannot open file 'C:\\Users\\kenne\\AppData\\Local\\Temp\\RtmpOO8Zi9\\file405054735731': No space left on device\n"
[1] "Tue Jan 25 14:18:07 2022\nTest completed with warnings for config: \n./test/test_configs/species_1.json\nand file: \n./test/test_data/TwelveMileGulchQuads2.envi\nwarnings: \nsimpleWarning in file(con, \"w\"): cannot open file 'C:\\Users\\kenne\\AppData\\Local\\Temp\\RtmpOO8Zi9\\file405018ad3060': No space left on device\n"
